on:
  push:
    tags:
      - 'dev*'

permissions:
  contents: write
  pages: write

env:
  - BASE_PATH: ${{ secrets.BASE_PATH }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # PREPARACION DEL ENTORNO
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      # INSTALACION DE DEPENDENCIAS Y BUILD
      - name: Build
        run: |
          pnpm install
          pnpm build

      # DESPLIEGUE EN GITHUB PAGES
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
